name: Clean Code Check
on:
  workflow_call:

jobs:
  clippy_and_udeps_check:
    runs-on: big-runner-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: clippy_and_udeps_check

      - name: Clippy Check
        run: cargo +nightly clippy --all-features --all-targets --tests

      - name: Clippy udeps
        run: cargo +nightly udeps --workspace --all-features --all-targets --tests
